"""Page shell: wraps a kind's rendered body in the document + inlined CSS.

The <head> inlines tokens.css (the design-system contract, shared with the
catalogue-design-system Storybook) followed by styles.css (the component styles).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .components import esc
from .kinds import KIND_DISPATCH

_ASSETS = Path(__file__).parent


def _load_css() -> str:
    tokens = (_ASSETS / "tokens.css").read_text(encoding="utf-8")
    styles = (_ASSETS / "styles.css").read_text(encoding="utf-8")
    return f"{tokens}\n{styles}"


def _mermaid_script(payload: dict) -> str:
    """Local mermaid init, themed from prefers-color-scheme to match tokens.

    CDN import is fine here: the renderer opens a local file:// page in a real
    browser, not a CSP-restricted Artifact.
    """
    if not payload.get("mermaid"):
        return ""
    return (
        '<script type="module">'
        "import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';"
        "const dark = matchMedia('(prefers-color-scheme: dark)').matches;"
        "mermaid.initialize({ startOnLoad: true, theme: dark ? 'dark' : 'default', "
        "themeVariables: dark"
        " ? { background: '#0d1117', primaryColor: '#161b22', primaryTextColor: '#e6edf3',"
        " primaryBorderColor: '#30363d', lineColor: '#4493f8' }"
        " : { background: '#ffffff', primaryColor: '#f6f8fa', primaryTextColor: '#1f2328',"
        " primaryBorderColor: '#d0d7de', lineColor: '#0969da' } });"
        "</script>"
    )


def render_page(kind: str, payload: dict) -> str:
    renderer = KIND_DISPATCH.get(kind)
    if not renderer:
        raise ValueError(f"Unknown kind '{kind}'. Expected one of: {', '.join(KIND_DISPATCH)}")

    (badge_text, accent, body), title, source_url = renderer(payload)

    source_link = ""
    if source_url:
        source_link = (
            f'<a class="source-link" href="{esc(source_url)}" '
            f'target="_blank" rel="noopener">↗ source</a>'
        )

    mermaid_script = _mermaid_script(payload) if kind == "explain" else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<style>{_load_css()}</style>
</head>
<body>
<div class="header header-{accent}">
<div class="badge badge-{accent}">{esc(badge_text)}</div>
<h1>{esc(title)}</h1>
{source_link}
</div>
{body}
<div class="footer">Generated by catalogue/{esc(kind)} · {datetime.now().strftime("%Y-%m-%d %H:%M")}</div>
{mermaid_script}
</body>
</html>"""
